### ISSUE TITLE
DonationAlerts Support?

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [iGoodie/TwitchSpawn#1]
Hi, this mod is very cool and I wanted to request a DonationAlerts (russian "Streamlabs") support for this. 
The donation info can be got using by this:
```
var socket = io("socket.donationalerts.ru:3001");
socket.emit('add-user', {token: "<Token>", type: "minor"});
socket.on('donation', function(msg){
  // Function to handle a donation by smth
});
```
And you get a JSON with this: 
```
{
	"id": "<id>",
	"alert_type": "1",
	"additional_data": "{\"randomness\":517}",
	"username": "<Name of the donator>",
	"amount": "50.00",
	"amount_formatted": "50",
	"amount_main": "50.00",
	"currency": "RUB",
	"message": "<message>",
	"date_paid": "2017-06-01 11:46:56",
	"emotes": null,
	"_is_test_alert": true
}
```
Hope you'll add this into the mod!

**Comment by iGoodie** [comment]
Thank you a lot for the suggestion! DonationAlerts tracer is going to be added with 1.13 capability update.

**Comment by iGoodie** [comment]
Thanks a lot for the suggestion! But the reference code you're showing is in a different language. Unfortunately due to lack of developer documents I am unable to add that tracer. However, your Pull Requests are always welcomed.

**Comment by DenisMasterHerobrine** [comment]
If I'll have some time, maybe I can turn this into Java code and make something, someone already done this in 1.7.10 and 1.10.2, and if I get sources of it, I'll make a PR with it, because it's very needed for some streamers. Thanks for answer.

**Comment by iGoodie** [comment]
With the new streamlabs socket api adaptation update, it is possible and easier to connect sockets. You can might take a reference from [SteamLabsSocket](https://github.com/iGoodie/TwitchSpawn/blob/streamlab-update/src/main/java/igoodie/twitchspawn/tracer/StreamLabsSocket.java) class. I am assigning this issue to you now! @DenisMasterHerobrine

**Comment by DenisMasterHerobrine** [comment]
I'll take a look and try to do something with it. Thanks for notification!

**Comment by DenisMasterHerobrine** [comment]
Done some work with it and uploaded in the fork, but seems some things I didn't understood properly, so support will not work, I guess, Any help is appreciated, as I'm a "slighty" newbie to modding, but I will try again and again to make the DA support working.

**Comment by iGoodie** [comment]
> Done some work with it and uploaded in the fork, but seems some things I didn't understood properly, so support will not work, I guess, Any help is appreciated, as I'm a "slighty" newbie to modding, but I will try again and again to make the DA support working.

No worries, [StreamLabsSocket.java](https://github.com/iGoodie/TwitchSpawn/blob/streamlab-update/src/main/java/igoodie/twitchspawn/tracer/StreamLabsSocket.java) will stay there as long as the Streamlabs keep serving the socket API. You can take your time, implement your own adaptation and even Minecraft commands. Then PR it when your testing results pass!

**Comment by DenisMasterHerobrine** [comment]
UPD: Finally got it worked. Without no documentation I have linked DonationAlerts to TwitchSpawn. 
Current Progress:
Link DonationAlerts to TwitchSpawn: Done
Make donations trigger rewards properly: WIP
