### ISSUE TITLE
[Improvement] Item parsing error lacking detailed information

### ISSUE THREAD

**Issue by Flemmli97** [iGoodie/TwitchSpawn#20]
**Describe the bug**
DROP action only allows vanilla item values. This is cause net.minecraft.command.arguments.ItemParser looks in the vanilla item registry and not the forge one. 

**To Reproduce**
Add in a modded item to a DROP action and it wont load.

**Version (please complete the following information):**
 - OS: MAC
 - TwitchSpawn Version: 0.4.9
 - Forge Version: 1.12.2-14.23.5.2847

**Comment by iGoodie** [comment]
It works with modded items as well. Could you share your TSL rule as well? You might be having a malformed item string in it

**Comment by Flemmli97** [comment]
nvm. it worked. item name was wrong

**Comment by iGoodie** [comment]
But I believe more detailed info on which part of the item string is wrong could be so handy! Also I believe someone in the Discord server also made me realize that. So i’m reopening the issue but changing the topic of it! 🎉

**Comment by iGoodie** [comment]
With 55df8d6 invalid item parsing now provides more information, instead of a generic invalid item message 🎉
