### ISSUE TITLE
[Bug] DISPLAYING not working for meta actions

### ISSUE THREAD

**Issue by Flemmli97** [iGoodie/TwitchSpawn#21]
**Describe the bug**
DISPLAYING doesnt work for meta actions such as BOTH or EITHER.
the tsl script is following (copied from the wiki):

EITHER
 DROP apple DISPLAYING %["Here comes apple!"]%
 OR
 DROP stick DISPLAYING %["Here comes stick!"]%
 OR
 NOTHING DISPLAYING %["What a pity! No reward for you."]
 ON Twitch Subscription%

and produces this: [https://imgur.com/7q79qd7](https://imgur.com/7q79qd7)

if e.g. only doing it like this:

DROP apple DISPLAYING %["Here comes apple!"]
 ON Twitch Subscription%

it shows the message properly.

**Version (please complete the following information):**
 - OS: MAC
 - TwitchSpawn Version: 0.4.9
 - Forge Version: 1.12.2-14.23.5.2847

**Comment by iGoodie** [comment]
It is now fixed with 07a2763. Thanks once again for letting me know! It will be published with the next build within a few days. 🎉
