### ISSUE TITLE
[Enhancement] More logging

### ISSUE THREAD

**Issue by MelanX** [iGoodie/TwitchSpawn#26]
It would be cool if the mod would log a bit more. Especially command feedback.
If there is a command which returns status code 0 it would be nice to know why it failed. I could not find any information whether in latest.log nor in debug.log.
Would be really nice :)

**Comment by iGoodie** [comment]
With 2.0, I will definitely consider this!

**Comment by iGoodie** [comment]
As of TwitchSpawn vX.6.3, `EXECUTE` TSL action logs feedback for failed command executions on the chat 🎉
I'll keep on adding more logging as I find any other spots lacking information :)
