### ISSUE TITLE
[Question] Is it possible to put a command from the streamlabs chatbot to execute the action?

### ISSUE THREAD

**Issue by Darcon31** [iGoodie/TwitchSpawn#27]
Good, I would like to know if instead of donating or following me, if it is possible to put it from a command (!boss or !void) of the chatbot, the action of invoking what you put could be executed or is there any other mod that can do it?
I do not know if I explain, thank you very much for everything

**Comment by iGoodie** [comment]
It is currently not possible. But soon, I'll work on a "Twitch Chat" TSL event with an internal cooldown :D

**Comment by iGoodie** [comment]
As of TwitchSpawn vX.6.3 `Twitch Chat Message` and `Loyalty Point Redemption` events are available to use!
You can now craft command rules 🎉 @Darcon31
