### ISSUE TITLE
Using 100% server RAM

### ISSUE THREAD

**Issue by Z0vris** [iGoodie/TwitchSpawn#42]
**Describe the bug**
I've been running the mod successfully on a server, but it keeps hogging 100% of the RAM of an 8gb server. Is there anything I can do the minimize that?

**To Reproduce**
No way to reproduce it, I expanded the server from 6gb to 8gb and it still hogs 100% ram usage.

**Expected behavior**

**Screenshots**
https://imgur.com/a/F7m0N2i

**Version (please complete the following information):**
 - OS: Windows 10
 - TwitchSpawn Version: twitchspawn_1.16.1-1.9.0
 - Forge Version: v35.1.37

**Comment by iGoodie** [comment]
Unfortunately, the issue doesn't have enough info to be resolved :c
