### ISSUE TITLE
[Request] Amount of Drops in config.json

### ISSUE THREAD

**Issue by ryuski** [iGoodie/TwitchSpawn#5]
I got the mod setup and it almost works perfectly for my needs. I was wondering if you could add in the support to drop more than 1 item at a time. I think it would be cool to drop 1 item for some event and 5 items for another event.

**Comment by iGoodie** [comment]
It is planned for next version adaptation update! Thanks for opening that as an issue tho, I'm assigning myself to this now

**Comment by iGoodie** [comment]
1.14 adaptation update closes this issue. With TwitchSpawn Language, your rules can have the amount of items to be dropped. (https://app.gitbook.com/@igoodie/s/twitchspawn/twitchspawn-language/tsl-actions#action-drop)
