### ISSUE TITLE
Minecraft 1.18.x support.

### ISSUE THREAD

**Issue by drraccoony** [iGoodie/TwitchSpawn#57]

**Comment by shadowcryptic** [comment]
1.18 will be released with TSL 2.0
It won't be for a while so sit tight

**Comment by DancerVlt69** [comment]
I'm not sure, but could it be that TSL 2.0 is already implemented since the MC 1.17 Java version?!

**Comment by iGoodie** [comment]
> I'm not sure, but could it be that TSL 2.0 is already implemented since the MC 1.17 Java version?! But it could also be, I misunderstand the Trello board!

Hey there! Sorry for the confusion, and my late reply! :)
TSL2.0 is not fully implemented yet. Parser is a part of the TSL2.0 implementation, yet it has other components too :D

**Comment by DancerVlt69** [comment]
Thanks for the info, that's let it show a little bit clearer.

btw: I use TwitchSpawn in MC 1.18(.x) - after some small changes... ;) 
@iGoodie  Don't worry, nobody will get this changed version! That's your part!

**Comment by iGoodie** [comment]
TwitchSpawn (with TSL1.0) is now available for 1.18.X :D
abbe278 closes this issue
