### ISSUE TITLE
FTBrank dos not allow Twitchspawn

### ISSUE THREAD

**Issue by Foss-Dyret** [iGoodie/TwitchSpawn#65]
we have FTBRank. and it requires being dev rank in order for it to send things through. so what permission does it require to have twitchspawn on?

**Comment by iGoodie** [comment]
`/ts` or `/twitchspawn` commands do not require any Minecraft Permission levels at all. 
However, TwitchSpawn internally requires executor to be either one of:
1. Marked as a streamer under `credentials.toml`
2. Marked as a moderator under `credentials.toml`
3. A command block
4. A dedicated server console

https://github.com/iGoodie/TwitchSpawn/blob/001ef6290d81102512a2c137e60934eb6cf3736c/src/main/java/net/programmer/igoodie/twitchspawn/configuration/CredentialsConfig.java#L237-L253

**Comment by Foss-Dyret** [comment]
I thank you many times for your answer. it also helped to find the error. and apologies for the inconvenience

**Comment by iGoodie** [comment]
Most welcome! No need for apologizes!
I'm glad it's sorted now 😄
