### ISSUE TITLE
Text is too big depending on GUI Scale Settings, a text font size setter is needed.

### ISSUE THREAD

**Issue by Khan8615** [iGoodie/TwitchSpawn#66]
**Describe the bug**
The display msg text is in the wrong size depending on your Minecraft GUI Scale Setting.

![guiscale](https://github.com/iGoodie/TwitchSpawn/assets/14542835/16f2e407-33c1-4519-b284-7710324aed15)

![image](https://github.com/iGoodie/TwitchSpawn/assets/14542835/d87f0390-b3b9-4eb6-b961-2c140eecf36f)

 - OS: [Windows 10]
 - TwitchSpawn Version: 1.16.1-1.9.0.jar
 - Forge Version: forge-1.16.5-36.2.39-installer.jar
 - OptiFine Version: OptiFine_1.16.5_HD_U_G8.jar

**Comment by iGoodie** [comment]
Hey there!

Unfortunately TwitchSpawn's displaying mechanism depends highly on Minecraft's `titles` command. 😢 
This behavior is planned to be changed in its next major update with TSL2.0 🎉
