### ISSUE TITLE
Errors thrown on events with 1.14.3-1.1.0

### ISSUE THREAD

**Issue by darkphan** [iGoodie/TwitchSpawn#8]
WIth the latest verison (1.14.3-1.1.0) an NPE is thrown whenever an event is triggered.

Snippets from the logs: https://pste.me/#/nk5bT

**Comment by iGoodie** [comment]
Thanks for pointing it out. That bug was caused because the mod failed to select default ruleset, where you have no custom `rules.darkphan.tsl` file.
Fixed with #583cc1a
Updated to v1.1.2
