### ISSUE TITLE
Donator name as entity custom name? 

### ISSUE THREAD

**Issue by JimiIT92** [iGoodie/TwitchSpawn#9]
I don't know if this is possibile, but if so i can't find anything on the documentation, but: is it possibile to include the donator name in commands? For example, on donation i want to spawn a creeper with the name of the donator, how can i do that? I tried including the ${actor} in the entity's nbt but this spawns a creeper with the name being literally ${actor}, not replacing the actual donator name. So, is it possibile to include this information in the command?

**Comment by iGoodie** [comment]
Hey there! Unfortunately, expression evaluation is currently only available on messages (Both on message configs and `DISPLAYING` parameters). However, expression evaluation is planned to be added to TSL actions real soon. 

If you are interested, in the mean time, you can see latest changes in our Discord Server! (https://discord.gg/KNxxdvN)

**Comment by JimiIT92** [comment]
Thank you for the answer! I'll keep an eye open ;)

**Comment by JimiIT92** [comment]
Edit: i've managed to get it work, i'll push the changes to my fork of your repository if you wish to take a look 😅

**Comment by iGoodie** [comment]
Sure thing, I can take a look at it @JimiIT92 ! 

PRs are always welcomed, as long as their commit logs satisfy the [Angular Commit Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)!

**Comment by iGoodie** [comment]
Perhaps setting up a CI for [Angular Commit Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153) soon might be a good idea 🤔
